# docker image for VPP

DOCKER_VPP_STEM = docker-vpp
DOCKER_VPP = $(DOCKER_VPP_STEM).gz
DOCKER_VPP_DBG = $(DOCKER_VPP_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_VPP)_PATH = $(DOCKERS_PATH)/$(DOCKER_VPP_STEM)

$(DOCKER_VPP)_DEPENDS += $(SWSS) $(LIBVPPCTL) $(LIBVPP_UTILS)
$(DOCKER_VPP)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS)
$(DOCKER_VPP)_DBG_DEPENDS += $(SWSS_DBG) $(LIBSWSSCOMMON_DBG)
$(DOCKER_VPP)_DBG_DEPENDS += $(LIBVPPCTL_DBG) $(LIBVPP_UTILS_DBG)

$(DOCKER_VPP)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

$(DOCKER_VPP)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BUSTER)

$(DOCKER_VPP)_VERSION = 1.0.0
$(DOCKER_VPP)_PACKAGE_NAME = vpp
$(DOCKER_VPP)_WARM_SHUTDOWN_BEFORE = syncd
$(DOCKER_VPP)_WARM_SHUTDOWN_AFTER = swss
$(DOCKER_VPP)_FAST_SHUTDOWN_BEFORE = swss

SONIC_DOCKER_IMAGES += $(DOCKER_VPP)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_VPP)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_VPP_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_VPP_DBG)

$(DOCKER_VPP)_CONTAINER_NAME = vpp
$(DOCKER_VPP)_RUN_OPT += --privileged -t
$(DOCKER_VPP)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_VPP)_RUN_OPT += -v /host/warmboot:/var/warmboot

$(DOCKER_VPP)_BASE_IMAGE_FILES += vppctl:/usr/bin/vppctl
$(DOCKER_VPP)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
